# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: refs.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'refs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrefs.proto\x12\x15stardew_valley.mcp.v1\x1a\x0c\x63ommon.proto\"\x14\n\x03Ref\x12\r\n\x05value\x18\x01 \x01(\t\"\xd4\x01\n\rRefResolution\x12\'\n\x03ref\x18\x01 \x01(\x0b\x32\x1a.stardew_valley.mcp.v1.Ref\x12\x30\n\x06status\x18\x02 \x01(\x0e\x32 .stardew_valley.mcp.v1.RefStatus\x12,\n\x04kind\x18\x03 \x01(\x0e\x32\x1e.stardew_valley.mcp.v1.RefKind\x12\x30\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x1c.stardew_valley.mcp.v1.ErrorH\x00\x88\x01\x01\x42\x08\n\x06_error*\xa4\x01\n\x07RefKind\x12\x18\n\x14REF_KIND_UNSPECIFIED\x10\x00\x12\x19\n\x15REF_KIND_WORLD_ENTITY\x10\x01\x12\x16\n\x12REF_KIND_CHARACTER\x10\x02\x12\x1b\n\x17REF_KIND_INVENTORY_ITEM\x10\x03\x12\x16\n\x12REF_KIND_CONTAINER\x10\x04\x12\x17\n\x13REF_KIND_UI_ELEMENT\x10\x05*\x8c\x01\n\tRefStatus\x12\x1a\n\x16REF_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13REF_STATUS_RESOLVED\x10\x01\x12\x14\n\x10REF_STATUS_STALE\x10\x02\x12\x18\n\x14REF_STATUS_NOT_FOUND\x10\x03\x12\x1a\n\x16REF_STATUS_UNSUPPORTED\x10\x04\x42\x1f\xaa\x02\x1cStardewValleyMcp.Protocol.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'refs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034StardewValleyMcp.Protocol.V1'
  _globals['_REFKIND']._serialized_start=289
  _globals['_REFKIND']._serialized_end=453
  _globals['_REFSTATUS']._serialized_start=456
  _globals['_REFSTATUS']._serialized_end=596
  _globals['_REF']._serialized_start=51
  _globals['_REF']._serialized_end=71
  _globals['_REFRESOLUTION']._serialized_start=74
  _globals['_REFRESOLUTION']._serialized_end=286
# @@protoc_insertion_point(module_scope)
