#!/usr/bin/env python3
"""从公共 Proto 单一来源生成 C# 与 Python 协议代码。"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROTO_ROOT = ROOT / "spec" / "proto"
CSHARP_TARGET = ROOT / "mod" / "src" / "StardewValleyMcp.Protocol" / "Generated"
PYTHON_TARGET = ROOT / "mcp" / "src" / "stardew_valley_mcp" / "protocol"
SCHEMA_GENERATOR = ROOT / "spec" / "conformance" / "generate_mcp_tool_schemas.py"
TOOL_SCHEMAS = ROOT / "spec" / "mcp" / "tool-schemas.json"
TOOL_CATALOG = ROOT / "mcp" / "src" / "stardew_valley_mcp" / "generated" / "tool_catalog.json"
CSHARP_CAPABILITY_CATALOG = CSHARP_TARGET / "CapabilityCatalogData.cs"
EXPECTED_PROTOC = "libprotoc 34.1"
GENERATED_PATTERNS = ("*.cs", "*_pb2.py", "*_pb2.pyi")


def run(command: list[str], cwd: Path | None = None) -> None:
    subprocess.run(command, cwd=cwd, check=True)


def check_protoc() -> str:
    completed = subprocess.run(
        ["protoc", "--version"],
        check=True,
        capture_output=True,
        text=True,
    )
    version = completed.stdout.strip()
    if version != EXPECTED_PROTOC:
        raise SystemExit(f"需要 {EXPECTED_PROTOC}，当前为 {version or 'unknown'}")
    return version


def patch_python_imports(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    text = re.sub(
        r"(?m)^import ([a-z0-9_]+_pb2) as ([a-zA-Z0-9_]+)$",
        r"from . import \1 as \2",
        text,
    )
    text = re.sub(
        r"(?m)^import ([a-z0-9_]+_pb2)$",
        r"from . import \1",
        text,
    )
    path.write_text(text, encoding="utf-8")


def generated_files(root: Path) -> dict[str, bytes]:
    files: dict[str, bytes] = {}
    for pattern in GENERATED_PATTERNS:
        for path in root.glob(pattern):
            files[path.name] = path.read_bytes()
    return files


def sync_generated(source: Path, target: Path, check: bool) -> None:
    expected = generated_files(source)
    actual = generated_files(target) if target.exists() else {}
    # CapabilityCatalogData.cs is generated from Manifest rather than protoc. It is the
    # only sibling excluded from the protoc stale-file gate.
    actual.pop("CapabilityCatalogData.cs", None)
    if check:
        if actual != expected:
            missing = sorted(expected.keys() - actual.keys())
            stale = sorted(actual.keys() - expected.keys())
            changed = sorted(name for name in expected.keys() & actual.keys() if expected[name] != actual[name])
            details = f"missing={missing} stale={stale} changed={changed}"
            raise SystemExit(f"生成文件不是最新状态: {target}: {details}")
        return

    target.mkdir(parents=True, exist_ok=True)
    for pattern in GENERATED_PATTERNS:
        for path in target.glob(pattern):
            if path.name != "CapabilityCatalogData.cs":
                path.unlink()
    for name, content in sorted(expected.items()):
        (target / name).write_bytes(content)


def sync_tool_catalog(check: bool) -> None:
    """生成完整公共 V1 descriptor 与 Tool Schema Catalog。"""
    schemas = json.loads(TOOL_SCHEMAS.read_text(encoding="utf-8"))
    manifest = load_manifest()
    capabilities = list(manifest["capabilities"])
    tools = list(schemas["tools"])
    capabilities.sort(key=lambda item: item["id"].encode("utf-8"))
    tools.sort(key=lambda item: item["name"].encode("utf-8"))
    if tuple(item["name"].removeprefix("stardew_") for item in tools) != tuple(item["id"] for item in capabilities):
        raise SystemExit("MCP Tool Catalog 与 Manifest capability 集合不一致")
    content = (json.dumps({"capabilities": capabilities, "tools": tools}, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode()
    if check:
        actual = TOOL_CATALOG.read_bytes() if TOOL_CATALOG.exists() else b""
        if actual != content:
            raise SystemExit("MCP Tool Catalog 生成物不是最新状态")
    else:
        TOOL_CATALOG.parent.mkdir(parents=True, exist_ok=True)
        TOOL_CATALOG.write_bytes(content)


def sync_csharp_capability_catalog(check: bool) -> None:
    """从 Manifest 生成 Mod 可复用的完整 CapabilityDescriptor 数据。"""
    manifest = load_manifest()
    capabilities = sorted(manifest["capabilities"], key=lambda item: item["id"].encode("utf-8"))
    enum = {
        "read_only": "SideEffect.ReadOnly",
        "mutating": "SideEffect.Mutating",
        "immediate": "ExecutionMode.Immediate",
        "long_running": "ExecutionMode.LongRunning",
    }
    lines = [
        "// <auto-generated />",
        "// Generated by scripts/generate_protocol.py from spec/capabilities/manifest.yaml.",
        "namespace StardewValleyMcp.Protocol.V1;",
        "",
        "internal static class CapabilityCatalogData",
        "{",
        "    internal static IReadOnlyDictionary<string, CapabilityDescriptor> Create() =>",
        "        new Dictionary<string, CapabilityDescriptor>(StringComparer.Ordinal)",
        "        {",
    ]
    for item in capabilities:
        risks = ", ".join(f'\"{risk}\"' for risk in sorted(item["risk"], key=lambda value: value.encode("utf-8")))
        lines.extend(
            [
                f'            ["{item["id"]}"] = new CapabilityDescriptor',
                "            {",
                f'                Id = "{item["id"]}",',
                f'                ContractVersion = "{item["contract_version"]}",',
                f'                SideEffect = {enum[item["side_effect"]]},',
                f'                Execution = {enum[item["execution"]]},',
                f'                Cancellable = {str(item["cancellable"]).lower()},',
                f'                DefaultTimeoutMs = {item["default_timeout_ms"]},',
                f'                MaxTimeoutMs = {item["max_timeout_ms"]},',
                f'                RequestType = nameof({item["request"]}),',
                f'                ResultType = nameof({item["result"]}),',
                f'                RequiredScope = "{item["required_scope"]}",',
                f'                Destructive = {str(item["destructive"]).lower()},',
                "                Risks = { " + risks + " }," if risks else "                Risks = { },",
                "            },",
            ]
        )
    lines.extend(["        };", "}", ""])
    content = "\n".join(lines).encode("utf-8")
    if check:
        actual = CSHARP_CAPABILITY_CATALOG.read_bytes() if CSHARP_CAPABILITY_CATALOG.exists() else b""
        if actual != content:
            raise SystemExit("C# CapabilityCatalogData 生成物不是最新状态")
    else:
        CSHARP_CAPABILITY_CATALOG.parent.mkdir(parents=True, exist_ok=True)
        CSHARP_CAPABILITY_CATALOG.write_bytes(content)


def load_manifest() -> dict[str, object]:
    """读取受版本控制的平面 capability manifest；无 PyYAML 时保留可用的受限解析。"""
    source = (ROOT / "spec" / "capabilities" / "manifest.yaml").read_text(encoding="utf-8")
    try:
        import yaml
    except ModuleNotFoundError:
        capabilities: list[dict[str, object]] = []
        current: dict[str, object] | None = None
        for line in source.splitlines():
            if line.startswith("  - id: "):
                current = {"id": line.removeprefix("  - id: ").strip()}
                capabilities.append(current)
                continue
            if current is None or not line.startswith("    ") or ":" not in line:
                continue
            key, raw = line.strip().split(":", 1)
            value = raw.strip()
            if value in {"true", "false"}:
                current[key] = value == "true"
            elif value.isdecimal():
                current[key] = int(value)
            elif value.startswith("[") and value.endswith("]"):
                current[key] = [item.strip() for item in value[1:-1].split(",") if item.strip()]
            else:
                current[key] = value
        return {"capabilities": capabilities}
    return yaml.safe_load(source)


def generate(check: bool) -> None:
    version = check_protoc()
    proto_files = sorted(PROTO_ROOT.glob("*.proto"))
    if not proto_files:
        raise SystemExit("spec/proto 中没有 Proto 文件")

    with tempfile.TemporaryDirectory(prefix="stardew-mcp-proto-") as raw_tmp:
        tmp = Path(raw_tmp)
        csharp_out = tmp / "csharp"
        python_out = tmp / "python"
        csharp_out.mkdir()
        python_out.mkdir()
        names = [path.name for path in proto_files]
        run(
            [
                "protoc",
                f"--proto_path={PROTO_ROOT}",
                f"--csharp_out={csharp_out}",
                f"--python_out={python_out}",
                f"--pyi_out={python_out}",
                *names,
            ],
            cwd=PROTO_ROOT,
        )
        for path in [*python_out.glob("*_pb2.py"), *python_out.glob("*_pb2.pyi")]:
            patch_python_imports(path)
        sync_generated(csharp_out, CSHARP_TARGET, check)
        sync_generated(python_out, PYTHON_TARGET, check)

    sync_csharp_capability_catalog(check)

    schema_command = [sys.executable, str(SCHEMA_GENERATOR)]
    if check:
        schema_command.append("--check")
    run(schema_command, cwd=ROOT)
    sync_tool_catalog(check)
    action = "checked" if check else "generated"
    print(f"protocol_{action} protoc={version} files={len(proto_files)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="只检查已提交生成物，不覆盖文件")
    args = parser.parse_args()
    generate(args.check)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
